id = "r"
name = "R"
version = "0.2.3"
schema_version = 1
description = "R language support."
repository = "https://github.com/ocsmit/zed-r"
authors = ["Owen Smith <owen8461@protonmail.com>", "Aymen Nasri <aymennasrii@proton.me>", "Changtao Li <60499240+lict99@users.noreply.github.com>"]
themes = []
icon_themes = []
languages = ["languages/r"]
capabilities = []

[lib]
kind = "Rust"
version = "0.4.0"

[grammars.r]
repository = "https://github.com/r-lib/tree-sitter-r"
rev = "a0d3e3307489c3ca54da8c7b5b4e0c5f5fd6953a"

[language_servers.r_language_server]
language = "R"
languages = []

[language_servers.r_language_server.language_ids]

[context_servers]

[slash_commands]

[indexed_docs_providers]
