# Catppuccin
# Theme create by: https://github.com/AnshumanNeon
# Update by(sort by time):
# 
# Thanks for all contributor!!

# If you want to make sidebar border display just set it same as sidebar background color

# Code syntax highlight theme (you can go to https://github.com/alecthomas/chroma/blob/master/styles to find one you like)
code_syntax_highlight = "catppuccin-mocha"

# ========= Border =========
file_panel_border = "#45eb45"
sidebar_border = "#45eb45"
footer_border = "#45eb45"

# ========= Border Active =========
file_panel_border_active = "#45eb45"
sidebar_border_active = "#45eb45"
footer_border_active = "#45eb45"
modal_border_active = "#45eb45"

# ========= Background (bg) =========
full_screen_bg = "#1e1e2e"
file_panel_bg = "#1e1e2e"
sidebar_bg = "#1e1e2e"
footer_bg = "#1e1e2e"
modal_bg = "#1e1e2e"

# ========= Foreground (fg) =========
full_screen_fg = "#45eb45"
file_panel_fg = "#45eb45"
sidebar_fg = "#45eb45"
footer_fg = "#45eb45"
modal_fg = "#45eb45"

# ========= Special Color =========
cursor = "#45eb45"
correct = "#a6e3a1"
error = "#f38ba8"
hint = "#73c7ec"
cancel = "#eba0ac"
# Gradient color can only have two color!
gradient_color = ["#89b4fa", "#cba6f7"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "#45eb45"
file_panel_top_path = "#45eb45"
file_panel_item_selected_fg = "#45eb45"
file_panel_item_selected_bg = "#000000"

# ========= Sidebar Special Items =========
sidebar_title = "#45eb45"
sidebar_item_selected_fg = "#000000"
sidebar_item_selected_bg = "#45eb45"
sidebar_divider = "#45eb45"

# ========= Modal Special Items =========
modal_cancel_fg = "#383838"
modal_cancel_bg = "#eba0ac"

modal_confirm_fg = "#383838"
modal_confirm_bg = "#89dceb"

# ========= Help Menu =========
help_menu_hotkey = "#89dceb"
help_menu_title = "#eba0ac"
