"$schema" = 'https://starship.rs/config-shema.json'

command_timeout = 10000

add_newline = true

format = """
$username(bg:#000000)\
[  ](bg:#000000)\
$hostname(bg:#000000)\
[  ](bg:#000000)\
$directory\
$fill\
$rlang\
$typst\
$python
$nix_shell
$character"""

[character]
# success_symbol = '[→](bold green)'
success_symbol = '[>](bold green)'
error_symbol = '[>](bold red)'

[directory]
style = "fg:#000000 bg:#45EB45"
format = "[>DIRECTORY](bg:#000000 fg:#45EB45) [ $path ]($style)"
truncation_length = 4
truncation_symbol = ".../"

[fill]
symbol = ""

[username]
style_user = "bg:#000000 fg:#45EB45"
style_root = "bg:#000000 fg:#45EB45"
format = "[>USER](bg:#000000 fg:#45EB45) [ $user ](bg:#45EB45 fg:#000000)"
aliases = { "jordi" = "JORDI"}
show_always = true

[hostname]
# format = "[$hostname ]($style)"
format = "[>HOST](bg:#000000 fg:#45EB45) [ $hostname ](bg:#45EB45 fg:#000000)"
style = "fg:#45EB45 bg:#000000"
ssh_only = false
aliases = { "nixos" = "NIXOS"}
