theme = "term16_dark"

[editor]
line-number = "relative"
mouse = true
rulers = [80]
text-width = 80

[editor.soft-wrap]
enable = true
wrap-at-text-width = true
wrap-indicator = ""

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"
